[hotspot]
src = "https://github.com/YunoHost-Apps/hotspot_ynh/tree/testing"

  [hotspot.arguments]
  wifi_ssid = "ClicHotspot"
  wifi_passphrase = "ClicHotspot"

[yeswiki]
default = true

  [yeswiki.arguments]
  domain = "."
  path = "wiki"
  wiki_name = "YesWiki"

  [yeswiki.extensions]
  plugins = [ "lms", "qrcode", "ferme" ]
  themes = [ ]
  configuration = { }

[cryptpad]

    [cryptpad.arguments]
    domain = "pads."

[peertube]

    [peertube.arguments]
    domain = "videos."

[hedgedoc]

    [hedgedoc.arguments]
    domain = "."
    path = "pads"

[nextcloud]

    [nextcloud.arguments]
    domain = "."
    path = "nextcloud"
